from dataclasses import dataclass


@dataclass
class Tribunal:
    nome: str
    max_pdf_mb: float


TRIBUNAIS = {
    "JFPR": Tribunal("JFPR", 11),
    "TJPR": Tribunal("TJPR", 4),
    "TRT9 - TRTPR": Tribunal("TRT9 - TRTPR", 1.5),
    "JFSC": Tribunal("JFSC", 11),
    "TJSC": Tribunal("TJSC", 11),
    "TRT12 - TRTSC": Tribunal("TRT12 - TRTSC", 1.5),
    "JFRS": Tribunal("JFRS", 11),
    "TJRS": Tribunal("TJRS", 11),
    "TRT4 - TRTRS": Tribunal("TRT4 - TRTRS", 1.5),
    "JFSP": Tribunal("JFSP", 10),
    "TJSP": Tribunal("TJSP", 10),
    "TRT2 - TRTSP": Tribunal("TRT2 - TRTSP", 10),
    "JFRJ": Tribunal("JFRJ", 11),
    "TJRJ": Tribunal("TJRJ", 5),
    "TRT1 - TRTRJ": Tribunal("TRT1 - TRTRJ", 10),
    "JFMT": Tribunal("JFMT", 20),
    "TJMT": Tribunal("TJMT", 5),
    "TRT23 - TRTMT": Tribunal("TRT23 - TRTMT", 10),
    "JFMG": Tribunal("JFMG", 11),
    "TJMG": Tribunal("TJMG", 2.5),
    "TRT3 - TRTMG": Tribunal("TRT3 - TRTMG", 2),
    "JFES": Tribunal("JFES", 11),
    "TJES": Tribunal("TJES", 3),
    "TRT17 - TRTES": Tribunal("TRT17 - TRTES", 3),
    "JFGO": Tribunal("JFGO", 20),
    "TJGO": Tribunal("TJGO", 6),
    "TRT18 - TRTGO": Tribunal("TRT18 - TRTGO", 6),
    "JFMS": Tribunal("JFMS", 10),
    "TJMS": Tribunal("TJMS", 2),
    "TRT24 - TRTMS": Tribunal("TRT24 - TRTMS", 1.5),
    "JFMA": Tribunal("JFMA", 20),
    "TJMA": Tribunal("TJMA", 10),
    "TRT16 - TRTMA": Tribunal("TRT16 - TRTMA", 10),
    "JFCE": Tribunal("JFCE", 5),
    "TJCE": Tribunal("TJCE", 2),
    "TRT7 - TRTCE": Tribunal("TRT7 - TRTCE", 12),
    "JFPI": Tribunal("JFPI", 20),
    "TJPI": Tribunal("TJPI", 3),
    "TRT22 - TRTPI": Tribunal("TRT22 - TRTPI", 10),
    "JFRN": Tribunal("JFRN", 5),
    "TJRN": Tribunal("TJRN", 10),
    "TRT21 - TRTRN": Tribunal("TRT21 - TRTRN", 10),
    "JFPB": Tribunal("JFPB", 1.5),
    "TJPB": Tribunal("TJPB", 1.5),
    "TRT13 - TRTPB": Tribunal("TRT13 - TRTPB", 7),
    "JFAL": Tribunal("JFAL", 2),
    "TJAL": Tribunal("TJAL", 2),
    "TRT19 - TRTAL": Tribunal("TRT19 - TRTAL", 1.5),
    "JFSE": Tribunal("JFSE", 5),
    "TJSE": Tribunal("TJSE", 2),
    "TRT20 - TRTSE": Tribunal("TRT20 - TRTSE", 3),
    "JFBA": Tribunal("JFBA", 20),
    "TJBA": Tribunal("TJBA", 1),
    "TRT5 - TRTBA": Tribunal("TRT5 - TRTBA", 10),
    "JFRR": Tribunal("JFRR", 20),
    "TJRR": Tribunal("TJRR", 10),
    "TRT11 - TRTRR": Tribunal("TRT11 - TRTRR", 3),
    "JFAP": Tribunal("JFAP", 20),
    "TJAP": Tribunal("TJAP", 3),
    "TRT8 - TRTAP": Tribunal("TRT8 - TRTAP", 10),
    "JFAM": Tribunal("JFAM", 20),
    "TJAM": Tribunal("TJAM", 2),
    "TRT11 - TRTAM": Tribunal("TRT11 - TRTAM", 3),
    "JFPA": Tribunal("JFPA", 20),
    "TJPA": Tribunal("TJPA", 20),
    "TRT8 - TRTPA": Tribunal("TRT8 - TRTPA", 10),
    "JFTO": Tribunal("JFTO", 20),
    "TJTO": Tribunal("TJTO", 11),
    "TRT10 - TRTTO": Tribunal("TRT10 - TRTTO", 2),
    "JFRO": Tribunal("JFRO", 20),
    "TJRO": Tribunal("TJRO", 1.5),
    "TRT14 - TRTRO": Tribunal("TRT14 - TRTRO", 3),
    "JFAC": Tribunal("JFAC", 20),
    "TJAC": Tribunal("TJAC", 20),
    "TRT14 - TRTAC": Tribunal("TRT14 - TRTAC", 3),
}
